#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3

teamname="opuSCOM2020"

BASEDIR=${BASEDIR}

player=${BASEDIR}"/sample_player"
coach=${BASEDIR}"/sample_coach"

config=${BASEDIR}"/player.conf"
config_dir=${BASEDIR}"/formations-dt"
coach_config=${BASEDIR}"/coach.conf"

formation_conf_dir=${BASEDIR}"/formations-dt"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"
opt="${opt} --formation-conf-dir ${formation_conf_dir}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"
coachopt="${coachopt} --formation-conf-dir ${formation_conf_dir}"

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
